objects:
  - position: { x: 0.0, y: 0.0, z: -7.0 }
    rotation: { angleX: 30.0, angleY: 60.0, angleZ: 0.0 }
    path: ../resources/cube.obj
  - position: { x: 1.4, y: 1.2, z: -6.0 }
    rotation: { angleX: 0.0, angleY: 10.0, angleZ: 40.0 }
    path: ../resources/cube.obj
